import { Slot } from '../componentSlots'
import { isArray } from '@vue/shared'

interface CompiledSlotDescriptor {
  name: string
  fn: Slot
}

/**
 * Compiler runtime helper for creating dynamic slots object
 * 主要是由于v-if和v-slot同时使用的时候，导致slot的结构不稳定
 * <Comp><template v-slot v-if></template></Comp>
 * 和
 * <Comp><template v-if></template></Comp>
 * 以上2中是不一样的，前者的slot default是动态的，所以是dynamic slot，后者是肯定有slot default
 * 所以是stable slot，不用显式的的去调用createSlots helper
 * createSlots({_:2}, [(_ctx.showIf)
      ? {
          name: "default",
          fn: _withCtx(() => [])
        }
      : undefined
  ])
 * @private
 */
export function createSlots(
  slots: Record<string, Slot>,
  dynamicSlots: (
    | CompiledSlotDescriptor
    | CompiledSlotDescriptor[]
    | undefined
  )[]
): Record<string, Slot> {
  for (let i = 0; i < dynamicSlots.length; i++) {
    const slot = dynamicSlots[i]
    // array of dynamic slot generated by <template v-for="..." #[...]>
    if (isArray(slot)) {
      for (let j = 0; j < slot.length; j++) {
        slots[slot[j].name] = slot[j].fn
      }
    } else if (slot) {
      // conditional single slot generated by <template v-if="..." #foo>
      slots[slot.name] = slot.fn
    }
  }
  return slots
}
